name: Docker pulls

on:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * *'

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: repos
        run: |
          date=$(date '+%Y-%m-%d')
          issue_text="Docker pulls $date:  <br>image,pulls_to_date,num_tags" 
          images=($(curl -s https://hub.docker.com/v2/repositories/staphb/?page_size=500 | jq -r '.results|.[]|.name'))
          echo ${images[@]}
          for image in ${images[@]}
          do
            echo "Getting pulls for $image"
            pulls=$(curl -s https://hub.docker.com/v2/repositories/staphb/$image/    | jq -r ".pull_count")
            echo "There are $pulls total pulls for $image"
            tags=$(curl -s https://hub.docker.com/v2/repositories/staphb/$image/tags | jq -r '.results[].name' | wc -l)
            echo "There are $tags total tags for $image"
            issue_text="$issue_text<br>${image},${pulls},${tags}"
          done
          echo $issue_text
          echo 'ISSUE_TEXT='$issue_text >> $GITHUB_ENV
          
      - name: Create Issue
        run: |
          gh issue create --title "Pulls" --body "$ISSUE_TEXT" --repo $GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
