name: Check versions

on:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * *'

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: repos
        run: |
          issue_text="Needing updates:  " 
          images=($(curl -s https://hub.docker.com/v2/repositories/staphb/?page_size=500 | jq -r '.results|.[]|.name'))
          echo ${images[@]}

          echo $issue_text
          cat versions.txt
          echo 'ISSUE_TEXT='$issue_text >> $GITHUB_ENV
          
      #- name: Create Issue
      #  run: |
      #    gh issue create --title "Pulls" --body "$ISSUE_TEXT" --repo $GITHUB_REPOSITORY
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
