name: Check latest versions

on: 
  workflow_dispatch:
  schedule:
    - cron: '30 4 1 * *'

run-name: Comparing latest versions with those in repository

jobs:
  list-repos:
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.set-matrix.outputs.json }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: StaPH-B/docker-builds
          
      - id: set-matrix
        name: set-matrix
        run: |
          grep github.com */*/Dockerfile | grep LABEL | grep website | sed 's/\"//g' | sed 's/,/\t/g' | sed 's/;/\t/g' |  sed 's/ /\t/g' | cut -f 1,2 | sed 's/\r$//g' | awk '{ split($1, arr, "/"); $1=arr[1] }1' | awk '{ split($2, arr, "/"); $2=arr[4]"/"arr[5] }1' | sort | uniq | awk '{ print $1 "," $2  }' | jq -ncR '[inputs]' > files.json
          cat files.json
          echo "json=$(cat files.json)" >> $GITHUB_OUTPUT
      
      - id: date
        name: Get current date
        run: |
          date=$(date '+%Y-%m-%d')
          echo "the date is $date"
          echo "date=$date" >> $GITHUB_OUTPUT

  get-versions:
    needs: list-repos
    if: needs.list-repos.outputs.json != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repos: ${{ fromJson(needs.list-repos.outputs.json) }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: StaPH-B/docker-builds
      
      - name: Parse tools and repos
        id: parse
        run: |
          tool=$(echo "${{ matrix.repos }}" | cut -f 1 -d "," )
          repo=$(echo "${{ matrix.repos }}" | cut -f 2 -d "," )
          echo "tool=$tool" >> $GITHUB_OUTPUT
          echo "repo=$repo" >> $GITHUB_OUTPUT

      - name: Get latest release
        uses: rez0n/actions-github-release@main
        continue-on-error: true
        id: latest_release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ steps.parse.outputs.repo }}
          type: "stable"
          
      - name: Check Directory
        if: steps.latest_release.outcome == 'success'
        id: check_directory
        run: |
          release=$(echo ${{ steps.latest_release.outputs.release }} | sed 's/^v//g' | sed 's/^V//g')

          ls -d ./${{ steps.parse.outputs.tool }}/*

          dir=$(ls -d ./${{ steps.parse.outputs.tool }}/* | grep ${release} | head -n 1 )

          if [ -d "$dir" ] && [ -n "${{ steps.latest_release.outputs.release }}" ]
          then
            echo "Found directory for ${{ steps.parse.outputs.tool }} version ${{ steps.latest_release.outputs.release }}"
            touch ${{ steps.date.outputs.date }}-update-${{ steps.parse.outputs.tool }}-${{ steps.latest_release.outputs.release }}-issue.txt
          elif [ -n "${{ steps.latest_release.outputs.release }}" ]
          then
            echo "No directory for ${{ steps.parse.outputs.tool }} version ${{ steps.latest_release.outputs.release }}!"
            echo "<br>- The tool ${{ steps.parse.outputs.tool }} is missing version ${{ steps.latest_release.outputs.release }} " > ${{ steps.date.outputs.date }}-update-${{ steps.parse.outputs.tool }}-${{ steps.latest_release.outputs.release }}-issue.txt
          else
            echo "No version for ${{ steps.parse.outputs.tool }} with ${{ steps.parse.outputs.repo }} repo!"
            touch ${{ steps.date.outputs.date }}-update-${{ steps.parse.outputs.tool }}-${{ steps.latest_release.outputs.release }}-issue.txt
          fi 

      - name: Creating version file
        if: steps.check_directory.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.date.outputs.date }}-update-${{ steps.parse.outputs.tool }}-${{ steps.latest_release.outputs.release }}-issue.txt
          retention-days: 1


  create-issue:
    needs: [ list-repos, get-versions ]
    runs-on: ubuntu-latest
    steps:
      - name: Downloading version file
        uses: actions/download-artifact@v4
      
      - name: Create text
        run: |
          cat ./artifact/${{ steps.date.outputs.date }}-update-*-issue.txt
          echo 'ISSUE_TEXT='$(cat ./artifact/update-*-issue.txt) >> $GITHUB_ENV

      - name: Create Issue
        run: |
          gh issue create --title "Version check" --body "$ISSUE_TEXT" --repo $GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
