name: Docker pulls

on:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * *'

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: repos
        run: |
          wget https://raw.githubusercontent.com/StaPH-B/docker-builds/master/README.md
          images=$(grep https://hub.docker.com/r/staphb/ README.md | \
            sed 's/.*(https:\/\/hub.docker.com\/r\/staphb\///g' | \
            sed 's/).*//g' | \
            grep -v "You can" | \
            grep . | \
            sort | \
            uniq)
          echo "image list :"
          echo ${images[@]}

          date=$(date '+%Y-%m-%d')
          issue_text="Docker pulls $date:  <br>image,pulls_to_date,num_tags"
          i=1
          for image in ${images[@]}
          do
            echo "Getting pulls for $image ( image $i of ${#images[@]} )"
            pulls=$(curl -s https://hub.docker.com/v2/repositories/staphb/$image/    | jq -r ".pull_count")
            sleep 3s
            echo "There are $pulls total pulls for $image"
            tags=$(curl -s https://hub.docker.com/v2/repositories/staphb/$image/tags | jq -r '.results[].name' | wc -l)
            sleep 3s
            echo "There are $tags total tags for $image"
            if [ -z "$tags"  ] ; then tags=0 ; fi
            if [ -z "$pulls" ] ; then pulls=0 ; fi
            issue_text="$issue_text<br>${image},${pulls},${tags}"
            i=$((i+1))
          done
          echo $issue_text
          echo 'ISSUE_TEXT='$issue_text >> $GITHUB_ENV
          
      - name: Create Issue
        run: |
          gh issue create --title "Pulls" --body "$ISSUE_TEXT" --repo $GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
